In [5]:

from pathlib import Path
import sys

print("Python utilizado:")
print(sys.executable)

print("\nCarpeta actual:")
print(Path.cwd())

print("\nContenido de la carpeta actual:")
for elemento in Path.cwd().iterdir():
    print(elemento.name)

Python utilizado:
c:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4\.venv314\Scripts\python.exe

Carpeta actual:
c:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4\src\rp_utils\notebooks

Contenido de la carpeta actual:
actividad_datos.ipynb
reportes

In [7]:
import sys
print(sys.executable)

c:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4\.venv314\Scripts\python.exe

In [8]:
import pandas as pd
import datasets

print("¡Todo funciona correctamente!")
print("Versión de pandas:", pd.__version__)
print("Versión de datasets:", datasets.__version__)

c:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4\.venv314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

¡Todo funciona correctamente!
Versión de pandas: 3.0.6
Versión de datasets: 5.1.0

In [9]:
from datasets import load_dataset

dataset = load_dataset("scikit-learn/iris", split="train")
df = dataset.to_pandas()

print("Dataset cargado correctamente")
print("Dimensiones:", df.shape)

df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Dataset cargado correctamente
Dimensiones: (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
print("Columnas originales:")
print(df.columns.tolist())

# Transformación: cambiar el nombre de una columna
df = df.rename(columns={"sepal_length": "longitud_sepalo"})

print("\nColumnas después de la transformación:")
print(df.columns.tolist())

df.head()

Columnas originales:
['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

Columnas después de la transformación:
['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
print("Columnas originales:")
print(df.columns.tolist())

# Transformación: cambiar el nombre de una columna
df = df.rename(columns={"SepalLengthCm": "longitud_sepalo"})

print("\nColumnas después de la transformación:")
print(df.columns.tolist())

df.head()

Columnas originales:
['Id', 'longitud_sepalo', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

Columnas después de la transformación:
['Id', 'longitud_sepalo', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

   Id  longitud_sepalo  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1              5.1           3.5            1.4           0.2  Iris-setosa
1   2              4.9           3.0            1.4           0.2  Iris-setosa
2   3              4.7           3.2            1.3           0.2  Iris-setosa
3   4              4.6           3.1            1.5           0.2  Iris-setosa
4   5              5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
from pathlib import Path
import sys

# Ubicar la carpeta principal del proyecto
RAIZ = Path.cwd().parents[2]

# Agregar la carpeta src a Python
sys.path.insert(0, str(RAIZ / "src"))

print("Carpeta del proyecto:", RAIZ)
print("¿Existe la carpeta src?", (RAIZ / "src").exists())
print("¿Existe rp_utils?", (RAIZ / "src" / "rp_utils").exists())

# Importar las clases
from rp_utils import HFDatasetLoader, DatasetSummarizer

print("¡Clases importadas correctamente!")

Carpeta del proyecto: c:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4
¿Existe la carpeta src? True
¿Existe rp_utils? True
¡Clases importadas correctamente!

In [18]:

from pathlib import Path

ruta_reporte = RAIZ / "reportes" / "resumen_dataset.txt"

resumidor = DatasetSummarizer(df)
resumidor.generar_resumen(ruta_reporte)

Resumen guardado en: C:\Users\USUARIO\OneDrive\Documentos\AD_2026Q4\reportes\resumen_dataset.txt

In [19]:

contenido = ruta_reporte.read_text(encoding="utf-8")
print(contenido)

RESUMEN DEL DATASET
========================================
Cantidad de filas: 150
Cantidad de columnas: 6

NOMBRES Y TIPOS DE DATOS
----------------------------------------
Id                   int64
longitud_sepalo    float64
SepalWidthCm       float64
PetalLengthCm      float64
PetalWidthCm       float64
Species                str

VALORES NULOS POR COLUMNA
----------------------------------------
Id                 0
longitud_sepalo    0
SepalWidthCm       0
PetalLengthCm      0
PetalWidthCm       0
Species            0

ESTADISTICAS DESCRIPTIVAS
----------------------------------------
                Id  longitud_sepalo  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
count   150.000000       150.000000    150.000000     150.000000    150.000000          150
unique         NaN              NaN           NaN            NaN           NaN            3
top            NaN              NaN           NaN            NaN           NaN  Iris-setosa
freq           NaN              NaN           NaN            NaN           NaN           50
mean     75.500000         5.843333      3.054000       3.758667      1.198667          NaN
std      43.445368         0.828066      0.433594       1.764420      0.763161          NaN
min       1.000000         4.300000      2.000000       1.000000      0.100000          NaN
25%      38.250000         5.100000      2.800000       1.600000      0.300000          NaN
50%      75.500000         5.800000      3.000000       4.350000      1.300000          NaN
75%     112.750000         6.400000      3.300000       5.100000      1.800000          NaN
max     150.000000         7.900000      4.400000       6.900000      2.500000          NaN